FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    postgresql-client \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

# Make the entrypoint script executable and set it as the ENTRYPOINT
# COPY entrypoint.sh /app/entrypoint.sh
# RUN chmod +x entrypoint.sh
# ENTRYPOINT ["/app/entrypoint.sh"]

EXPOSE 8000
